---
title: "Explore Fishing Capacity Data"
author: "Julia Blanchard"
date: "2022-12-19"
output: html
---

## Access data

First, read in Rousseau et al. 2023 country-level data from  the IMAS Data Portal:

```{r}
library(shiny)
library(plotly)
library(DT)
library(tidyverse)
library(patchwork)


effort<-read_csv(file="https://data.imas.utas.edu.au/attachments/1241a51d-c8c2-4432-aa68-3d2bae142794/CapacityCountryLevel_Detailed.csv")[,-1]

# convert character to factor for key drop-down variables

effort$Country<-as.factor(effort$Country)
effort$Sector<-as.factor(effort$Sector)
effort$Gear<-as.factor(effort$Gear)
```

## Explore Data

For each country you can check to see the fraction of the time series that are empirical data and the fraction estimated by GAM. This is specified as either "Data" or GAM under the column "MethodNV" for each row of data.

```{r, echo=FALSE}
#  filtered_data<-subset(effort,
#        Country %in% "GBR" & Sector %in% "I" & Gear %in% "Trawl_Bottom")
#  
#  p1 <- ggplot(filtered_data, aes_string(x="Year", y="NV",colour="MethodNV")) +
#    geom_point(alpha=0.5) +
#    facet_wrap(~Length_Category,nrow =1)
#    theme_minimal() +
#    ylab("Number of vessels")
#    
#    
#  
#  p2 <-ggplot(filtered_data, aes_string(x="Year", y="GT",colour="MethodGT")) +
#    geom_point(alpha=0.5) +
#    facet_wrap(~Length_Category,nrow =1)
#    theme_minimal() +
#    ylab("Gross Tonnage")
#    
#  
#   p3 <-ggplot(filtered_data, aes_string(x="Year", y="P",colour="MethodP")) +
#    geom_point(alpha=0.5) +
#    facet_wrap(~Length_Category,nrow =1)
#    theme_minimal() +
#    ylab("Power")
#    
#    p1 /p2 / p3
#  
#  print(filtered_data)
# 

```

####### Shiny App

```{r, echo=FALSE}
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      h2("Explore Country-level Fishing Capacity"),
      selectInput(inputId = "Country", label = "Country",
                  choices = levels(effort$Country),
                  selected = "GBR"),
            selectInput(inputId = "Sector", "Sector",
                    choices = levels(effort$Sector),
                    selected = "I"),
             selectInput(inputId = "Gear", "Gear",
                               choices = levels(effort$Gear),
                              selected = "Trawl_Bottom"),
      downloadButton(outputId = "download_data", label = "Download"),
    ),
    mainPanel(
      plotlyOutput(outputId = "plot"), br(),
      em("Reconstructed fishing capacity time series showing years where original data and estimated values were used to estimate fishing effort"),
      br(), br(), br(),
      DT::dataTableOutput(outputId = "table")
    )
  )
)


server <- function(input, output) {
  filtered_data <- reactive({
    subset(effort,Country %in% input$Country & Sector %in% input$Sector & Gear %in% input$Gear)})
  
  output$plot <- renderPlotly({
    ggplotly({
        p1 <- ggplot(filtered_data(), aes_string(x="Year", y="NV",colour="MethodNV")) +
          geom_point(alpha=0.5) +
          facet_wrap(~Length_Category,nrow =1)
          theme_minimal() +
          ylab("Number of vessels")
   
 
         p2 <-ggplot(filtered_data(), aes_string(x="Year", y="GT",colour="MethodGT")) +
           geom_point(alpha=0.5) +
           facet_wrap(~Length_Category,nrow =1)
           theme_minimal() +
           ylab("Gross Tonnage")
       
 
         p3 <-ggplot(filtered_data(), aes_string(x="Year", y="P",colour="MethodP")) +
           geom_point(alpha=0.5) +
           facet_wrap(~Length_Category,nrow =1)
           theme_minimal() +
           ylab("Power")
     
         subplot(p1,p2,p3,nrows=3,shareX=F,shareY=F,margin=0.1)

    })
  })
  
  output$table <- DT::renderDataTable({
    filtered_data()
  })
  
  output$download_data <- downloadHandler(
    filename = "download_data.csv",
    content = function(file) {
      data <- filtered_data()
      write.csv(data, file, row.names = FALSE)
    }
  )
  
}

shinyApp(ui = ui, server = server)


```